In [1]:
import pandas as pd

In [2]:
file_dir = "C:/Users/annab/ucb/Movies-ETL"

In [3]:
kaggle_metadata = pd.read_csv(f"{file_dir}/movies_metadata.csv", low_memory=False)
ratings = pd.read_csv(f"{file_dir}/ratings.csv")

In [4]:
kaggle_metadata.sample(n=5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
20559,False,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,42455,tt0069715,es,And Now The Screaming Starts,"In the late 18th century, two newlyweds move i...",...,1973-04-26,0.0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Technicolor film set in a ghostly gothic man...,And Now The Screaming Starts,False,6.4,12.0
42341,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.brandnerkaspar-derfilm.de/,17008,tt1148770,de,Die Geschichte vom Brandner Kaspar,No overview found.,...,2008-10-16,0.0,105.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,NaN,Die Geschichte vom Brandner Kaspar,False,6.1,7.0
28573,False,NaN,6400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,191121,tt2359810,hi,रान्झाना,A small-town boy needs to break through the cl...,...,2013-06-21,18000000.0,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Raanjhanaa,False,6.3,34.0
42849,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,203273,tt1518191,en,Manche Hunde beißen,"Halliday (19), Casey (14) and baby Severino ha...",...,2010-10-01,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Some Dogs Bite,False,4.7,3.0
39824,False,"{'id': 24717, 'name': 'Johan Falk GSI Collecti...",0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,136071,tt2239108,sv,Johan Falk: Alla råns moder,"GSI second in command, Sophie Nordh, flips gan...",...,2012-10-24,0.0,97.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,Johan Falk: Alla råns moder,False,6.3,6.0